// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWLnxPVSif7loUJTAmSsMu2nQSYMsNUKE',
    appId: '1:1060675010358:web:01e7cae0898a7c4b863d97',
    messagingSenderId: '1060675010358',
    projectId: 'goodnight-ai',
    authDomain: 'goodnight-ai.firebaseapp.com',
    storageBucket: 'goodnight-ai.appspot.com',
    measurementId: 'G-Y5EHB6PMF0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOP8gnTQGQQae5dNC9npKX8MRPMn7P6gk',
    appId: '1:1060675010358:android:f5671add7b25bb9b863d97',
    messagingSenderId: '1060675010358',
    projectId: 'goodnight-ai',
    storageBucket: 'goodnight-ai.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtg3rCWCyN6qNcKTTqnIDlAF14Uo_przQ',
    appId: '1:1060675010358:ios:a3d97da2d8fe8103863d97',
    messagingSenderId: '1060675010358',
    projectId: 'goodnight-ai',
    storageBucket: 'goodnight-ai.appspot.com',
    iosClientId: '1060675010358-krga1b6pmvc1pvjh8hpa8nhl2f66ljkq.apps.googleusercontent.com',
    iosBundleId: 'com.goodnightai.goodnightAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtg3rCWCyN6qNcKTTqnIDlAF14Uo_przQ',
    appId: '1:1060675010358:ios:a3d97da2d8fe8103863d97',
    messagingSenderId: '1060675010358',
    projectId: 'goodnight-ai',
    storageBucket: 'goodnight-ai.appspot.com',
    iosClientId: '1060675010358-krga1b6pmvc1pvjh8hpa8nhl2f66ljkq.apps.googleusercontent.com',
    iosBundleId: 'com.goodnightai.goodnightAi',
  );
}
